### PR TITLE
Changes `.` to `,` to ensure valid code

### PR DESCRIPTION
**Pull request by tesar-tech**

### CODE REVIEW

**Comment by jscasca** [comment]
@tesar-tech thanks for the contirbution but I cannot merge if you don't sign up the CLA. Otherwise, I will patch that in the next fix I submit

**Comment by tesar-tech** [comment]
As I understand from your [Contributors Licence Agreement ](http://cla.moxiecode.com/?r=tinymce%2Ftinymce-blazor&pr=801), the only option how to contribute is to disable my GitHub e-mail privacy?

**Comment by jscasca** [comment]
@tesar-tech I believe that to be the case. Unfortunately, I do not handle those processes :(

**Comment by tesar-tech** [comment]
(😞)
In that case, I am giving up my contribution.

**Pull request closed without merging**
